### ISSUE TITLE
Correção Exercício 3.13.1

### ISSUE THREAD

**Issue by mathiasgheno** [MelissaBG/react-ts-razf4e#1]
# Correção

> Combinando flexbox e media queries, faça o layout de exibição dos cads do youtube. Para uma resolução baixa deve ser exibido dois cards. Para uma resolução alta deve ser exibido quatro cards. 

![image](https://user-images.githubusercontent.com/14915619/183270980-e5ce08ef-b064-4402-82a4-12a6ed2409d9.png)

![image](https://user-images.githubusercontent.com/14915619/183270987-cd485ef9-8530-40c9-9cc4-942a6b1aa05c.png)

Você está renderizando 1 para resolução baixa e 2 para alta. Tirando isso tudo ok. 

**Nota:** 10! Parabéns 🥳 

# Comentários

Numa aplicação real, é importante ter um local único para configurar variáveis globais que podem ser utilizadas em diversas paginas ou components. Variáveis CSS podem ser usadas para isso. 

```css
:root {
  --resolucao-alta: 800px;
  --resolucao-baixa: 550px;
}
```

Para acessar esse valor basta utilizar o `var`. Veja abaixo.

```css
@media screen and (min-width: var(--resolucao-alta)) {
  .card-video-um{
    width: 350px;
  }

}
@media screen and (min-width: var(--resolucao-baixa)) {
  .card-video-um{
    width: 320px;
  }
}
```
